# Catch-all server for direct IP access (warning page + logging)
# Generated by nginx-hardening-framework

server {
    listen 80 default_server;
    server_name _;
    access_log /var/log/nginx/ip_access_attempts.log;
    root /var/www/security-warning;
    index index.html;

    location / {
        try_files $uri /index.html;
    }
}

server {
    listen 443 ssl default_server;
    server_name _;
    access_log /var/log/nginx/ip_access_attempts.log;

    ssl_certificate {{SSL_CERT}};
    ssl_certificate_key {{SSL_KEY}};

    root /var/www/security-warning;
    index index.html;

    location / {
        try_files $uri /index.html;
    }
}
