# Host-only hardening for {{DOMAIN}}
# Generated by nginx-hardening-framework

# Hide nginx version (fingerprinting protection)
server_tokens off;

# Slowloris protection & resource abuse reduction
client_body_timeout 15s;
client_header_timeout 15s;
send_timeout 15s;
keepalive_timeout 30s;

# Request size control (safe default)
client_max_body_size 10m;

# Block uncommon HTTP methods
if ($request_method !~ ^(GET|POST|HEAD|OPTIONS)$) {
    return 405;
}

# Core security headers
add_header X-Content-Type-Options "nosniff" always;
add_header X-Frame-Options "SAMEORIGIN" always;
add_header Referrer-Policy "strict-origin-when-cross-origin" always;
add_header Permissions-Policy "geolocation=(), microphone=(), camera=()" always;

# Browser isolation headers
add_header Cross-Origin-Opener-Policy "same-origin" always;
add_header Cross-Origin-Resource-Policy "same-origin" always;

{{CSP_HEADER}}
